- name: Setup dotnet
  hosts: localhost
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Get dotnet install script
      command: wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh

    - name: Change script permissions
      command: chmod +x ./dotnet-install.sh

    - name: Install dotnet sdk 8
      command: ./dotnet-install.sh --channel 8.0

    - name: Install dotnet sdk 6
      command: ./dotnet-install.sh --channel 6.0
