- name: Setup dotnet
  hosts: localhost
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Purge microsoft packages
      command: sudo dpkg --purge packages-microsoft-prod 

    - name: Install microsoft packages
      command: sudo dpkg -i packages-microsoft-prod.deb

    - name: Install dotnet-sdk 8
      apt:
        name: dotnet-sdk-8.0
        update_cache: true

    - name: Install dotnet-sdk 6
      apt:
        name: dotnet-sdk-6.0
        update_cache: true
