- name: setting up node
  hosts: localhost
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Install Ca certificatesn, curl, gnupg
      apt:
        update_cache=true
        pkg:
          - ca-certificates
          - curl
          - gnupg

    - name: Make keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Download and imort the Nodesrouce GPG key
      command: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key 

    - name: Dearmor
      command: gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

    - name: Create deb repository
      command: echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"

    - name: Tee
      command: tee /etc/apt/sources.list.d/nodesource.list

    - name: Install node
      apt:
        name=nodejs
        update_cache=true
      
