- name: Set up zsh
  hosts: localhost
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Install zsh
      apt:
        name: zsh
        update_cache: yes

    - name: Set zsh as default shell
      command: sudo chsh -s $(which zsh)

    - name: Install Oh My Zsh
      command: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
